---
apiVersion: v1
kind: Pod

metadata:
  name: sg-count
  namespace: cloud
spec:
  containers:
  - name: sg-count
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
---


